name: starship-manifestjs
version: v0.2.12

chains:
  - id: manifest-ledger-beta
    name: custom
    image: ghcr.io/liftedinit/manifest-ledger:v0.0.1-alpha.13
    home: /root/.manifest
    binary: manifestd
    prefix: manifest
    denom: umfx
    coins: 10000000000000umfx
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    repo: https://github.com/liftedinit/manifest-ledger
    numValidators: 1
    env:
      # This is the address of the `genesis` entry defined in
      # https://github.com/cosmology-tech/starship/blob/main/starship/charts/devnet/configs/keys.json
      - name: POA_ADMIN_ADDRESS
        value: manifest1qjtcxl86z0zua2egcsz4ncff2gzlcndzrtglqv
    scripts:
      createGenesis:
        file: scripts/create-manifest-genesis.sh
    genesis:
      app_state:
        staking:
          params:
            bond_denom: "upoa"
            min_commission_rate: "0"
        mint:
          params:
            mint_denom: "notused"
            blocks_per_year: "6311520"
            inflation_rate_change: "0"
            inflation_max: "0"
            inflation_min: "0"
          minter:
            inflation: "0"
            annual_provisions: "0"
        slashing:
          params:
            slash_fraction_double_sign: "0"
            slash_fraction_downtime: "0"
        distribution:
          params:
            community_tax: "0"
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8001
    resources:
      cpu: "0.2"
      memory: "512Mi"
  - id: cosmos-2
    name: cosmoshub
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8002
    resources:
      cpu: "0.2"
      memory: "512Mi"

relayers:
  - name: manifest-cosmos
    type: hermes
    replicas: 1
    chains:
      - manifest-ledger-beta
      - cosmos-2
    resources:
      cpu: "0.2"
      memory: "512Mi"

registry:
  enabled: true
  ports:
    rest: 8081
  resources:
    cpu: "0.2"
    memory: "512Mi"

explorer:
  enabled: true
  type: ping-pub
  ports:
    rest: 8080
  resources:
    cpu: "0.2"
    memory: "512Mi"
