name: manifestjs
version: v1.2.1

chains:
  - id: manifest-ledger-beta
    name: manifest
    image: ghcr.io/liftedinit/manifest-ledger:v0.0.1-alpha.12
    numValidators: 1
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8007
    resources:
      cpu: "0.2"
      memory: "200M"
  - id: cosmos-2
    name: cosmoshub
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8003
    resources:
      cpu: "0.2"
      memory: "200M"

relayers:
  - name: manifest-cosmos
    type: hermes
    replicas: 1
    chains:
      - manifest-ledger-beta
      - cosmos-2
    resources:
      cpu: "0.1"
      memory: "100M"

registry:
  enabled: true
  ports:
    rest: 8081
    grpc: 9091
  resources:
    cpu: "0.1"
    memory: "100M"

exposer:
  resources:
    cpu: "0.1"
    memory: "100M"

faucet:
  resources:
    cpu: "0.1"
    memory: "100M"
